# Generated by Django 2.2.13 on 2020-08-15 08:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the Organization', max_length=255, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address_line_1', models.CharField(blank=True, help_text='Adress of the Organization', max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, help_text='Address contd.', max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, help_text='Zip code of the Organization', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City where the Organization is located', max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Country where the Organization is located', max_length=2, null=True)),
                ('accepted_terms_and_conditions', models.BooleanField(default=False, help_text='Organization has accepted the terms and conditions and the privacy policy.')),
                ('has_free_access', models.BooleanField(default=False, help_text='This organization should have free access.')),
                ('subscription_paid_until', models.DateField(blank=True, help_text='Organization has full access until', null=True)),
                ('language_preference', models.CharField(blank=True, choices=[('en-us', 'English'), ('nb', 'Norwegian')], help_text='Language preference', max_length=25, null=True)),
                ('survey_language_preference', models.CharField(choices=[('en-us', 'English'), ('nb', 'Norwegian')], default='en-us', help_text='What language should surveys have when sent out?', max_length=25)),
                ('stripe_id', models.CharField(blank=True, default=None, help_text='Subscribers Customer object ID in Stripe API', max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default=None, help_text='Subscribers Subscription object ID in Stripe API', max_length=255, null=True)),
                ('stripe_subscription_quantity', models.PositiveSmallIntegerField(default=0, help_text='Current number of users/employees that are billed for', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000000)])),
                ('owner', models.OneToOneField(blank=True, help_text='User who owns this Organization', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='What was the event?', max_length=255)),
                ('comment', models.TextField(blank=True, help_text='More info on event', null=True)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='Time of event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
