# Generated by Django 2.2.10 on 2020-04-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the plan', max_length=60)),
                ('description', models.CharField(help_text='A short description of the plan', max_length=255)),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Montly price', max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, help_text='Yearly price', max_digits=10)),
            ],
        ),
    ]
