# Generated by Django 2.2.10 on 2020-04-17 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the plan', max_length=60)),
                ('description', models.CharField(help_text='A short description of the plan', max_length=255)),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Montly price', max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, help_text='Yearly price', max_digits=10)),
                ('is_paid', models.CharField(choices=[('n', 'No'), ('y', 'Yes')], default='n', help_text='Is the plan a paid plan?', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_current_plan_expires', models.DateField(default=django.utils.timezone.now)),
                ('payment_interval', models.CharField(blank=True, choices=[('m', 'Monthly'), ('y', 'Yearly')], default='', help_text='Payment interval', max_length=1)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
