# Generated by Django 2.2.10 on 2020-04-18 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.CharField(help_text='What is the argument?', max_length=255)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Set a priority (0-100):', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('badge_type', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('succes', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='secondary', help_text='Should a badge accompany the argument?', max_length=30)),
                ('badge_text', models.CharField(help_text='What should the badge (if any) say?', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Is this argument active (supposed to be visible)?')),
            ],
        ),
    ]
