# Generated by Django 2.2.10 on 2020-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_added_payment_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_current_plan_expires',
            field=models.DateField(blank=True, help_text='The date the current stripe subscription ends', null=True),
        ),
    ]
