# Generated by Django 2.2.10 on 2020-04-18 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_salesargument'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='additional_employee_monthly_price',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Montly price per additional employee', max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='additional_employee_yearly_price',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Yearly price per additional employee', max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_be_picked',
            field=models.BooleanField(default=True, help_text='This plan should be available to pick for visitors'),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_be_viewed',
            field=models.BooleanField(default=True, help_text='This plan should be visible to visitors'),
        ),
        migrations.AddField(
            model_name='plan',
            name='included_employees',
            field=models.PositiveSmallIntegerField(default=10, help_text='The number of employees that are included', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000000)]),
        ),
        migrations.AddField(
            model_name='plan',
            name='sales_argument',
            field=models.ManyToManyField(blank=True, help_text='Select sales arguments for this plan', to='website.SalesArgument'),
        ),
        migrations.AddField(
            model_name='plan',
            name='show_price',
            field=models.BooleanField(default=True, help_text='Should the price be displayed?'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Special price for this Subscriber (leave blank to use the plan's price.)", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesargument',
            name='badge_text',
            field=models.CharField(blank=True, default=None, help_text='What should the badge (if any) say?', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesargument',
            name='badge_type',
            field=models.CharField(blank=True, choices=[('No set', None), ('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default=None, help_text='Should a badge accompany the argument?', max_length=30),
        ),
    ]
