# Generated by Django 2.2.10 on 2020-05-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200424_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='date_current_plan_expires',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='date_last_synced_with_stripe',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='flagged_interest_in_plan',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='status',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='SalesArgument',
        ),
    ]
