# Generated by Django 2.2.10 on 2020-04-17 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_current_plan_expires',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 17, 12, 30, 58, 721609, tzinfo=utc), null=True),
        ),
    ]
