# Generated by Django 2.2.10 on 2020-04-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200418_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Plan'),
        ),
    ]
