# Generated by Django 2.2.10 on 2020-04-17 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200417_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_current_plan_expires',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
