# Generated by Django 2.2.10 on 2020-06-09 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_auto_20200529_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='stripe_subscription_id',
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the Organization', max_length=255, null=True)),
                ('address_line_1', models.CharField(blank=True, help_text='Adress of the Organization', max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, help_text='Address contd.', max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, help_text='Zip code of the Organization', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City where the Organization is located', max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Country where the Organization is located', max_length=2, null=True)),
                ('stripe_id', models.CharField(blank=True, default=None, help_text='Subscribers Customer object ID in Stripe API', max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default=None, help_text='Subscribers Subscription object ID in Stripe API', max_length=255, null=True)),
                ('owner', models.OneToOneField(blank=True, help_text='User who owns this Organization', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
