# Generated by Django 2.2.10 on 2020-06-09 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_organization_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_quantity',
            field=models.PositiveSmallIntegerField(default=0, help_text='Current number of users/employees that are billed for', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000000)]),
        ),
    ]
