# Generated by Django 2.2.10 on 2020-04-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200419_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default=None, help_text='Subscribers Subscription object ID in Stripe API', max_length=255, null=True),
        ),
    ]
