# Generated by Django 2.2.10 on 2020-04-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_subscriber_payment_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_current_plan_expires',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='payment_interval',
            field=models.CharField(blank=True, choices=[('m', 'Monthly'), ('y', 'Yearly')], default='', help_text='Payment interval', max_length=1),
        ),
    ]
