# Generated by Django 2.2.10 on 2020-04-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_subscriber_stripe_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='custom_price',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='date_current_plan_expires',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='payment_interval',
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_plan_id',
            field=models.CharField(blank=True, default=None, help_text='This Plans Plan-object ID in Stripe API', max_length=255, null=True),
        ),
    ]
