# Generated by Django 2.2.10 on 2020-07-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_organization_stripe_subscription_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
