# Generated by Django 2.2.10 on 2020-04-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200419_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='additional_employee_monthly_price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='additional_employee_yearly_price',
        ),
    ]
