# Generated by Django 2.2.10 on 2020-07-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accepted_terms_and_conditions',
            field=models.BooleanField(default=False, help_text='Organization has accepted the terms and conditions'),
        ),
    ]
