# Generated by Django 2.2.10 on 2020-04-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200419_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_current_plan_expires',
            field=models.DateField(blank=True, help_text='The date the current strupe subscription ends', null=True),
        ),
    ]
