# Generated by Django 2.2.10 on 2020-07-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_organization_accepted_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='accepted_terms_and_conditions',
            field=models.BooleanField(default=False, help_text='Organization has accepted the terms and conditions and the privacy policy.'),
        ),
    ]
