# Generated by Django 2.2.10 on 2020-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200417_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_paid',
            field=models.CharField(choices=[('n', 'No'), ('y', 'Yes')], default='n', help_text='Is the plan a paid plan?', max_length=1),
        ),
    ]
