# Generated by Django 2.2.10 on 2020-04-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_subscriber_date_current_plan_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='status',
            field=models.CharField(blank=True, default=None, help_text='The subscrition status of the Subscriber', max_length=35, null=True),
        ),
    ]
