# Generated by Django 2.2.13 on 2020-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200722_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_paid_until',
            field=models.DateField(blank=True, help_text='Organization has full access until', null=True),
        ),
    ]
