# Generated by Django 2.2.10 on 2020-04-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_subscriber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_last_synced_with_stripe',
            field=models.DateField(blank=True, help_text='The date this object was synced with Stripe', null=True),
        ),
    ]
