# Generated by Django 2.2.13 on 2020-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_organization_subscription_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_free_access',
            field=models.BooleanField(default=False, help_text='This organization should have free access.'),
        ),
    ]
