# Generated by Django 2.2.10 on 2020-04-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_subscriber_date_last_synced_with_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='flagged_interest_in_plan',
            field=models.CharField(blank=True, help_text='Subscriber is interested in this plan', max_length=60, null=True),
        ),
    ]
