# Generated by Django 2.2.13 on 2020-08-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_organization_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='survey_language_preference',
            field=models.CharField(choices=[('en-us', 'English'), ('nb', 'Norwegian')], default='en-us', help_text='What language should surveys have when sent out?', max_length=25),
        ),
        migrations.AlterField(
            model_name='organization',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('nb', 'Norwegian')], help_text='Language preference', max_length=25, null=True),
        ),
    ]
