# Generated by Django 2.2.10 on 2020-06-03 12:56

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country where the Organization is located', max_length=2, null=True),
        ),
    ]
