# Generated by Django 2.2.10 on 2020-04-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20200425_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dimension',
            field=models.CharField(blank=True, default=None, help_text='The dimension this Question fits under', max_length=250, null=True),
        ),
    ]
