# Generated by Django 2.2.10 on 2020-06-04 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20200603_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(help_text='Organization where this Employee is employed', on_delete=django.db.models.deletion.CASCADE, to='surveys.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.OneToOneField(blank=True, help_text='User who owns this Organization', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(help_text='Organization that owns this survey', null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.Organization'),
        ),
    ]
