# Generated by Django 2.2.10 on 2020-06-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20200604_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(help_text='Organization where this Employee is employed', on_delete=django.db.models.deletion.CASCADE, to='website.Organization'),
        ),
        migrations.AlterField(
            model_name='productsetting',
            name='organization',
            field=models.ForeignKey(help_text='Organization this setting applies to', on_delete=django.db.models.deletion.CASCADE, to='website.Organization'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(help_text='Organization that owns this survey', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Organization'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
