# Generated by Django 2.2.10 on 2020-06-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20200604_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='intanswer',
            name='survey_instance',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='active_products',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='productsetting',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='productsetting',
            name='product',
        ),
        migrations.RemoveField(
            model_name='question',
            name='product',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='product',
        ),
        migrations.RemoveField(
            model_name='surveyinstance',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='surveyinstance',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='survey_instance',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='IntAnswer',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductSetting',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyInstance',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
    ]
