# Generated by Django 2.2.10 on 2020-04-26 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_question_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='surveys_remain_open_days',
            field=models.SmallIntegerField(default=21, help_text='How many days should surveys be open for this organization', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='dimension',
            field=models.CharField(blank=True, default=None, help_text='The dimension or category for this Question', max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='ProductSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='This product is active for this organization')),
                ('survey_interval', models.SmallIntegerField(default=90, help_text='How many days between each survey', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(730)])),
                ('last_survey_open', models.DateField(blank=True, help_text='Last opening date of survey with this product/prganization combo', null=True)),
                ('last_survey_close', models.DateField(blank=True, help_text='Last closing date of survey with this product/prganization combo', null=True)),
                ('organization', models.ForeignKey(help_text='Organization this setting applies to', on_delete=django.db.models.deletion.CASCADE, to='surveys.Organization')),
                ('product', models.ForeignKey(help_text='Product this setting applies to', on_delete=django.db.models.deletion.CASCADE, to='surveys.Product')),
            ],
        ),
    ]
