# Generated by Django 2.2.10 on 2020-06-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0006_organization_stripe_subscription_quantity'),
        ('surveys', '0004_auto_20200610_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='First name of Employee', max_length=255, null=True)),
                ('email', models.EmailField(help_text='Email of Respondent', max_length=254)),
                ('last_name', models.CharField(blank=True, help_text='Last name of Respondent', max_length=255, null=True)),
                ('receives_surveys', models.BooleanField(default=True, help_text='This Respondent should receive surveys from the Organization')),
                ('organization', models.ForeignKey(help_text='Organization where this Respondent is employed', on_delete=django.db.models.deletion.CASCADE, to='website.Organization')),
            ],
        ),
    ]
