# Generated by Django 2.2.10 on 2020-04-29 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20200428_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='surveys_remain_open_days',
        ),
        migrations.AddField(
            model_name='productsetting',
            name='surveys_remain_open_days',
            field=models.SmallIntegerField(default=21, help_text='How many days should surveys be open for this organization', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
    ]
