# Generated by Django 2.2.10 on 2020-06-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('surveys', '0006_ratiosurveyitem_survey_surveyitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instruction', models.CharField(blank=True, max_length=255, null=True)),
                ('opt_out', models.BooleanField(default=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_surveys.scale_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RatioScale',
            fields=[
                ('scale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Scale')),
                ('min_value', models.SmallIntegerField(default=0)),
                ('max_value', models.SmallIntegerField(default=0)),
                ('min_value_description', models.CharField(blank=True, max_length=255, null=True)),
                ('max_value_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surveys.scale',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulation', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('inverted', models.BooleanField(default=False)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Dimension')),
            ],
        ),
        migrations.AddField(
            model_name='dimension',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Instrument'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Scale'),
        ),
    ]
