# Generated by Django 2.2.10 on 2020-05-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20200429_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instruction_string',
            field=models.CharField(blank=True, default=None, help_text='Short text instructing how to answer the question', max_length=255, null=True),
        ),
    ]
