# Generated by Django 2.2.10 on 2020-05-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_question_instruction_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinstance',
            name='completed',
            field=models.BooleanField(default=False, help_text='This SI has been completed'),
        ),
    ]
