# Generated by Django 2.2.10 on 2020-06-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('surveys', '0009_auto_20200614_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratiosurveyitem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='surveyitem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='ratiosurveyitem',
            name='max_score_numeric',
        ),
        migrations.RemoveField(
            model_name='ratiosurveyitem',
            name='min_score_numeric',
        ),
        migrations.RemoveField(
            model_name='ratiosurveyitem',
            name='normalized_end_score_numeric',
        ),
        migrations.AddField(
            model_name='ratiosurveyitem',
            name='average',
            field=models.FloatField(blank=True, default=None, help_text='Average of scores for this item in this survey', null=True),
        ),
        migrations.AddField(
            model_name='ratiosurveyitem',
            name='scale',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='surveys.RatioScale'),
        ),
        migrations.AddField(
            model_name='surveyitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_surveys.surveyitem_set+', to='contenttypes.ContentType'),
        ),
    ]
