# Generated by Django 2.2.10 on 2020-06-14 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20200614_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyitem',
            name='formulation',
        ),
        migrations.RemoveField(
            model_name='surveyitem',
            name='instruction_string',
        ),
        migrations.RemoveField(
            model_name='surveyitem',
            name='n_invited',
        ),
        migrations.AddField(
            model_name='survey',
            name='n_completed',
            field=models.IntegerField(default=0, help_text='Number of respondents'),
        ),
        migrations.AddField(
            model_name='survey',
            name='n_incomplete',
            field=models.IntegerField(default=0, help_text='Number of respondents'),
        ),
        migrations.AddField(
            model_name='survey',
            name='n_invited',
            field=models.IntegerField(default=0, help_text='Number of respondents'),
        ),
        migrations.AddField(
            model_name='surveyitem',
            name='item_dimension',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='surveys.Dimension'),
        ),
        migrations.AddField(
            model_name='surveyitem',
            name='item_formulation',
            field=models.CharField(blank=True, help_text='A question or statement to confront Respondents with', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surveyitem',
            name='item_inverted',
            field=models.BooleanField(default=False),
        ),
    ]
