# Generated by Django 2.2.10 on 2020-06-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('surveys', '0011_auto_20200614_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.Respondent')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyInstanceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_surveys.surveyinstanceitem_set+', to='contenttypes.ContentType')),
                ('survey_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.SurveyInstance')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='ratiosurveyitem',
            name='scale',
        ),
        migrations.AlterField(
            model_name='surveyitem',
            name='item_dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='surveys.Dimension'),
        ),
        migrations.CreateModel(
            name='RatioSurveyInstanceItem',
            fields=[
                ('surveyinstanceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.SurveyInstanceItem')),
                ('answer', models.SmallIntegerField(blank=True, default=None, help_text='Number of respondents', null=True)),
                ('survey_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.RatioSurveyItem')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surveys.surveyinstanceitem',),
        ),
    ]
