# Generated by Django 2.2.10 on 2020-06-17 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_auto_20200615_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.Instrument'),
        ),
    ]
