# Generated by Django 2.2.10 on 2020-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_surveysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='This survey is finished forever'),
        ),
    ]
