# Generated by Django 2.2.10 on 2020-06-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_survey_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysetting',
            name='last_survey_close',
            field=models.DateField(blank=True, help_text='Last closing date of survey with this product/prganization combo', null=True),
        ),
        migrations.AddField(
            model_name='surveysetting',
            name='last_survey_opened',
            field=models.DateField(blank=True, help_text='Last opening date of survey with this product/prganization combo', null=True),
        ),
    ]
