# Generated by Django 2.2.10 on 2020-06-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_auto_20200619_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveysetting',
            old_name='last_survey_opened',
            new_name='last_survey_open',
        ),
    ]
