# Generated by Django 2.2.10 on 2020-06-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_auto_20200619_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinstance',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyinstanceitem',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveysetting',
            name='is_active',
            field=models.BooleanField(default=False, help_text='This instrument is active for this organization'),
        ),
    ]
