# Generated by Django 2.2.10 on 2020-06-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_auto_20200621_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='n_not_started',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='n_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='n_incomplete',
            field=models.IntegerField(default=0),
        ),
    ]
