# Generated by Django 2.2.10 on 2020-06-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_auto_20200621_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinstance',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
