# Generated by Django 2.2.10 on 2020-06-22 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('surveys', '0021_surveyinstance_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_completed', models.IntegerField(default=0)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Dimension')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_surveys.dimensionresult_set+', to='contenttypes.ContentType')),
                ('survey', models.ForeignKey(help_text='Organization that owns this survey', null=True, on_delete=django.db.models.deletion.PROTECT, to='surveys.Survey')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterField(
            model_name='ratiosurveyinstanceitem',
            name='answer',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='RatioScaleDimensionResult',
            fields=[
                ('dimensionresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.DimensionResult')),
                ('average', models.FloatField(blank=True, default=None, help_text='Average of scores for this dimension in this survey', null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surveys.dimensionresult',),
        ),
    ]
