# Generated by Django 2.2.10 on 2020-06-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_auto_20200622_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysetting',
            name='surveys',
            field=models.ManyToManyField(to='surveys.Survey'),
        ),
    ]
