# Generated by Django 2.2.10 on 2020-07-02 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_auto_20200627_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='slug_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scale',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='surveysetting',
            name='surveys_remain_open_days',
            field=models.SmallIntegerField(default=7, help_text='How many days should surveys be open for this organization', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
    ]
