# Generated by Django 2.2.10 on 2020-07-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_respondentemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='formulation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='surveyitem',
            name='item_formulation',
            field=models.TextField(blank=True, help_text='A question or statement to confront Respondents with', null=True),
        ),
    ]
