# Generated by Django 2.2.10 on 2020-07-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_surveyinstance_consent_was_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinstanceitem',
            name='chose_to_not_answer',
            field=models.BooleanField(default=False),
        ),
    ]
