# Generated by Django 2.2.13 on 2020-08-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0029_surveyinstanceitem_chose_to_not_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='description_en_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='description_nb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='name_nb',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='slug_name_en_us',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='slug_name_nb',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
