# Generated by Django 2.2.13 on 2020-08-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_auto_20200805_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='instruction_en_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scale',
            name='instruction_nb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
