# Generated by Django 2.2.13 on 2020-08-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0031_auto_20200805_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratioscale',
            name='max_value_description_en_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ratioscale',
            name='max_value_description_nb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ratioscale',
            name='min_value_description_en_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ratioscale',
            name='min_value_description_nb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
