# Generated by Django 2.2.13 on 2020-08-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0032_auto_20200805_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='description_en_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='description_nb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='name_nb',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
