# Generated by Django 2.2.13 on 2020-08-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0033_auto_20200805_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='formulation_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='formulation_nb',
            field=models.TextField(null=True),
        ),
    ]
