# Generated by Django 2.2.13 on 2020-08-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0034_auto_20200805_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyitem',
            name='item_formulation_en_us',
            field=models.TextField(blank=True, help_text='A question or statement to confront Respondents with', null=True),
        ),
        migrations.AddField(
            model_name='surveyitem',
            name='item_formulation_nb',
            field=models.TextField(blank=True, help_text='A question or statement to confront Respondents with', null=True),
        ),
    ]
