# Generated by Django 2.2.13 on 2020-08-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0035_auto_20200805_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysetting',
            name='survey_language_preference',
            field=models.CharField(choices=[('en-us', 'English'), ('nb', 'Norsk')], default='en-us', help_text='What language should surveys have when sent out?', max_length=25),
        ),
    ]
