# Generated by Django 2.2.13 on 2020-08-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0036_surveysetting_survey_language_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveysetting',
            name='survey_language_preference',
        ),
    ]
